drop table jugadores_old

CREATE TABLE  jugadores_old (	
  id int,
  Name character varying(255),
  Age int,
  Photo character varying(255),
  Nationality character varying(255),
  Flag character varying(255),
  Overall character varying(255),
  Potential character varying(255),
  Club character varying(255),
  Logo character varying(255),
  Value character varying(255),
  Wage character varying(255),
  Special character varying(255),
  Preferred_Foot character varying(255),
  International_Reputation character varying(255),	
  Weak_Foot character varying(255),
  Skill_Moves character varying(255),
  Work_Rate character varying(255),
  Body_Type	character varying(255),
  Real_Face character varying(255),
  Position character varying(255),
  Jersey_Number character varying(255), 
  Joined character varying(255),
  Loaned_From character varying(255),
  Contract_Valid_Until character varying(255),
  Height character varying(255),
  Weight character varying(255),
  LS  character varying(255),
  ST character varying(255),
  RS character varying(255),
  LW character varying(255),
  LF character varying(255),
  CF character varying(255),
	RF character varying(255),
	RW character varying(255),
	LAM character varying(255),
	CAM character varying(255),
	RAM character varying(255),
	LM character varying(255),
	LCM character varying(255),
	CM character varying(255),
	RCM character varying(255),
	RM character varying(255),
	LWB character varying(255),
	LDM character varying(255),
	CDM character varying(255),
	RDM character varying(255),
	RWB character varying(255),
	LB character varying(255),
	LCB character varying(255),
	CB character varying(255),
	RCB character varying(255),
  RB character varying(255),
  Crossing int,Finishing int,HeadingAccuracy int,ShortPassing int,Volleys int,Dribbling int,Curve int,FKAccuracy int,LongPassing int,BallControl int,Acceleration int,SprintSpeed int,Agility int,Reactions int,Balance int,ShotPower int,Jumping int,Stamina int,Strength int,LongShots int,Aggression int,Interceptions int,Positioning int,Vision int,Penalties int,Composure int,Marking int,StandingTackle int,SlidingTackle int,GKDiving int,GKHandling int,GKKicking int,GKPositioning int,
  GKReflexes int,
  Release_Clause character varying(255)
);

COPY jugadores_old FROM '/Users/fnc/Desktop/Futbol/FIFA 2019_reloaded.csv' DELIMITER ';' CSV HEADER ENCODING 'UTF8'

SELECT id, name, age, photo, nationality, flag, overall, potential, club, logo, value, wage, special, preferred_foot, international_reputation, weak_foot, skill_moves, work_rate, body_type, real_face, "position", jersey_number, joined, loaned_from, contract_valid_until, height, weight, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, crossing, finishing, headingaccuracy, shortpassing, volleys, dribbling, curve, fkaccuracy, longpassing, ballcontrol, acceleration, sprintspeed, agility, reactions, balance, shotpower, jumping, stamina, strength, longshots, aggression, interceptions, positioning, vision, penalties, composure, marking, standingtackle, slidingtackle, gkdiving, gkhandling, gkkicking, gkpositioning, gkreflexes, release_clause
	FROM public.jugadores_old;
	
CREATE TABLE  jugadores (	
  id int,
  Name character varying(255),
  Age int,
  Photo character varying(255),
  Nationality character varying(255),
  Flag character varying(255),
  Overall character varying(255),
  Potential character varying(255),
  Club character varying(255),
  Logo character varying(255),
  Value character varying(255),
  Wage character varying(255),
  Special character varying(255),
  Preferred_Foot character varying(255),
  International_Reputation character varying(255),	
  Weak_Foot character varying(255),
  Skill_Moves character varying(255),
  Work_Rate character varying(255),
  Body_Type	character varying(255),
  Real_Face character varying(255),
  Position character varying(255),
  Jersey_Number character varying(255), 
  Joined character varying(255),
  Loaned_From character varying(255),
  Contract_Valid_Until character varying(255),
  Height character varying(255),
  Weight character varying(255),
  LS  character varying(255),
  ST character varying(255),
  RS character varying(255),
  LW character varying(255),
  LF character varying(255),
  CF character varying(255),
	RF character varying(255),
	RW character varying(255),
	LAM character varying(255),
	CAM character varying(255),
	RAM character varying(255),
	LM character varying(255),
	LCM character varying(255),
	CM character varying(255),
	RCM character varying(255),
	RM character varying(255),
	LWB character varying(255),
	LDM character varying(255),
	CDM character varying(255),
	RDM character varying(255),
	RWB character varying(255),
	LB character varying(255),
	LCB character varying(255),
	CB character varying(255),
	RCB character varying(255),
  RB character varying(255),
  Crossing int,Finishing int,HeadingAccuracy int,ShortPassing int,Volleys int,Dribbling int,Curve int,FKAccuracy int,LongPassing int,BallControl int,Acceleration int,SprintSpeed int,Agility int,Reactions int,Balance int,ShotPower int,Jumping int,Stamina int,Strength int,LongShots int,Aggression int,Interceptions int,Positioning int,Vision int,Penalties int,Composure int,Marking int,StandingTackle int,SlidingTackle int,GKDiving int,GKHandling int,GKKicking int,GKPositioning int,
  GKReflexes int,
  Release_Clause character varying(255)
);

insert into jugadores

SELECT id, name, age, photo, nationality, flag, overall, potential, club, logo, replace (value,'Û','€'), replace (wage,'Û','€'), special, preferred_foot, international_reputation, weak_foot, skill_moves, work_rate, body_type, real_face, "position", jersey_number, joined, loaned_from, contract_valid_until, height, weight, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, crossing, finishing, headingaccuracy, shortpassing, volleys, dribbling, curve, fkaccuracy, longpassing, ballcontrol, acceleration, sprintspeed, agility, reactions, balance, shotpower, jumping, stamina, strength, longshots, aggression, interceptions, positioning, vision, penalties, composure, marking, standingtackle, slidingtackle, gkdiving, gkhandling, gkkicking, gkpositioning, gkreflexes, replace (release_clause,'Û','€')
	FROM public.jugadores_old;
